---
steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: build builder
    dir: /workspace/cli
    args:
      - --destination=gcr.io/$PROJECT_ID/${_BUILDER}
      - --cache=true
      - --context
      - /workspace/cli
      - --dockerfile
      - Dockerfile.builder

  - name: 'gcr.io/$PROJECT_ID/${_BUILDER}'
    id: 'test, build, release'
    dir: '/workspace/cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -x
        set -e
        . /build/virtualenvs/*/bin/activate
        make release
        poetry version | cut -f2 -d ' ' > .version
    env:
      - CODECOV_TOKEN=${_CODECOV_TOKEN}
      - COMMIT_SHA=$COMMIT_SHA
  - name: gcr.io/cloud-builders/git
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -x
        set -e
        git init
        git remote add origin https://github.com/n0npax/lime-comb.git
        git fetch
        git tag $(cat ./cli/.version) $COMMIT_SHA
        git push origin $(cat ./cli/.version)

substitutions:
  _BUILDER: lime-comb-builder
images:
  - 'gcr.io/$PROJECT_ID/${_BUILDER}'
timeout: 900s
