---
steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: build builder
    dir: cli
    args:
      - --destination=gcr.io/$PROJECT_ID/${_BUILDER}
      - --cache=true
      - --context
      - /workspace/cli
      - --dockerfile
      - Dockerfile.builder

  - name: 'gcr.io/$PROJECT_ID/${_BUILDER}'
    id: 'test, build, release'
    dir: 'cli'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        set -x
        poetry env use python
        make CI=true $(git log -1 --pretty=raw | grep "Bumps:" | cut -f2 -d ':' | xargs -n1 -I ITEM echo BUMP=ITEM)
    env:
      - 'GIT_DISCOVERY_ACROSS_FILESYSTEM=1'

  - name: gcr.io/cloud-builders/git
    id: "push tags"
    args:
      - push
      - --tags
    env:
      - 'GIT_DISCOVERY_ACROSS_FILESYSTEM=1'

substitutions:
  _BUILDER: lime-comb-builder
images:
  - 'gcr.io/$PROJECT_ID/${_BUILDER}'
timeout: 900s