---
steps:
  - name: 'python:3.7.5-alpine'
    id: 'test, build, release'
    dir: 'cli'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        set -x
        apk add make build-base python3-dev libc-dev libffi-dev libressl-dev openssl-dev linux-headers curl
        pip install --upgrade pip
        pip install poetry
        make CI=true
