---
steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: build builder
    dir: /workspace/cli
    args:
      - --destination=gcr.io/$PROJECT_ID/${_BUILDER}
      - --cache=true
      - --context
      - /workspace/cli
      - --dockerfile
      - Dockerfile.builder

  - name: 'gcr.io/$PROJECT_ID/${_BUILDER}'
    id: 'test, build, release'
    dir: '/workspace/cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -x
        set -e
        . /build/virtualenvs/*/bin/activate
        poetry env info
        make release
    env:
      - CODECOV_TOKEN=${_CODECOV_TOKEN}
      - COMMIT_SHA=$COMMIT_SHA


substitutions:
  _BUILDER: lime-comb-builder
images:
  - 'gcr.io/$PROJECT_ID/${_BUILDER}'
timeout: 900s