---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build builder
    dir: /workspace/cli
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/${_BUILDER}:latest
      docker build -t gcr.io/$PROJECT_ID/${_BUILDER}:latest --cache-from gcr.io/$PROJECT_ID/${_BUILDER}:latest -f Dockerfile.builder /workspace/cli

  - name: 'gcr.io/$PROJECT_ID/${_BUILDER}'
    id: test, build, release
    dir: /workspace/cli
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -x
        set -e
        . /build/virtualenvs/*/bin/activate
        make release
        poetry version | cut -f2 -d ' ' > .version
    env:
      - CODECOV_TOKEN=${_CODECOV_TOKEN}
      - COMMIT_SHA=$COMMIT_SHA

  - name: gcr.io/cloud-builders/git
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        git init
        git remote add origin https://n0npax:${_GITHUB_TOKEN}@github.com/n0npax/lime-comb.git
        git fetch
        git tag $(cat ./cli/.version) $COMMIT_SHA || exit 0
        git push origin $(cat ./cli/.version) -f
    env:
      - GITHUB_TOKEN=${_GITHUB_TOKEN}
      - COMMIT_SHA=$COMMIT_SHA

substitutions:
  _BUILDER: lime-comb-builder
images:
  - 'gcr.io/$PROJECT_ID/${_BUILDER}'
timeout: 900s
