---
steps:
  - name: "gcr.io/$PROJECT_ID/${_BUILDER}"
    id: test, build, release
    dir: /workspace/api
    entrypoint: "bash"
    args:
      - -ex
      - "-c"
      - |
        poetry export -f requirements.txt --without-hashes > requirements.txt
        pip3 install -r requirements.txt
        make cover
    env:
      - COMMIT_SHA=$COMMIT_SHA
      - PYTHONPATH=/workspace/api
    secretEnv:
      - PYPI_TOKEN
      - CODECOV_TOKEN

  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy
    dir: /workspace/api
    args:
      - app
      - deploy
      - -q

substitutions:
  _BUILDER: lime-comb-builder
images:
  - "gcr.io/$PROJECT_ID/${_BUILDER}"
timeout: 900s

secrets:
  - kmsKeyName: projects/lime-comb/locations/global/keyRings/ci-keyring-29ec094/cryptoKeys/ci-cryptokey-1ef48c7
    secretEnv:
      CODECOV_TOKEN: CiQAxUJzVxPLBBLyGjoINzP+vCFUNyKY+6ZxQ17+w7n6o7GkXiwSTQCJK84AWpDEnBe+WCRmJiaNFjrgsnpLzYnHJ1T34x26EQUoI+vVn1ShxbEtizLSQG5YxnFWQbG+vxQFTXniKj3KvzEEb6OGi3Xr8A+G
      PYPI_TOKEN: CiQAxUJzVzEXDbYwRtuGqz2IrPLxpUdN5feJ9wlZ3KNK9rYabxwS8gEAiSvOAO/1BHXZjCF2alEbz1gghy5fwTrE5HA4v0EsDSKFYpkWU3saQWxF4GQmlwAoUAJngaG6wyDCm+aNNPBpzQGUiNcjbKRv/KKNs5hSjts6ptu3PUDpDJhXl66Qsfq091+DRjrEo2Z0zjeR2pYtRjw46YLCn9LFky9yBH06b93irma0a5pOhMMOeGXd8ODulIqKwZPa7IWr4KC+DmQKdwAlcoXMeEaw4fsR9SBoNU0oHyu/w12a2IOmuhT2RgGfsNiBb+r4xbqAt0heb75o/ybgEJfWq6PxZG83GqMK4ma8ln5P1lAPkaIUABN22VJong==
