---
steps:
  - name: 'node:10-buster'
    id: 'deploy'
    dir: 'web'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eo pipefail
        npm install -g firebase-tools
        firebase deploy --project $PROJECT_ID
